In [1]:
import pandas as pd
import numpy as np

# Create raw data
data = {
    "Name": ["Aman", "Saurav", "Karan", "Shubham", "Abhishek", "Missing", "Sameer"],
    "Age": [22, 23, "Missing", 22, 25, 24, 26],
    "Marks": [85, "Missing", 88, 90, 56, 72, "Missing"],
    "Subject": ["Math", "Physics", "Math", "Chemistry", "Math", "Physics", "Chemistry"]
}

df = pd.DataFrame(data)

# Replace "Missing" with NaN (null)
df.replace("Missing", np.nan, inplace=True)

# Convert Age and Marks to numeric
df["Age"] = pd.to_numeric(df["Age"])
df["Marks"] = pd.to_numeric(df["Marks"])

print(df)

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5       NaN  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry

C:\Users\Ruchi\AppData\Local\Temp\ipykernel_21896\2511132955.py:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("Missing", np.nan, inplace=True)

In [2]:
df.shape

(7, 4)

In [3]:
df.dtypes

Name        object
Age        float64
Marks      float64
Subject     object
dtype: object

In [7]:
df.describe()

             Age      Marks
count   6.000000   5.000000
mean   23.666667  78.200000
std     1.632993  14.254824
min    22.000000  56.000000
25%    22.250000  72.000000
50%    23.500000  85.000000
75%    24.750000  88.000000
max    26.000000  90.000000

In [8]:
df[["Name", "Marks"]]

       Name  Marks
0      Aman   85.0
1    Saurav    NaN
2     Karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5       NaN   72.0
6    Sameer    NaN

In [9]:
df[df["Marks"] > 80]

      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry

In [11]:
df[(df["Age"] > 22) & (df["Marks"] > 80)]

Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []

In [13]:
df["Subject"].value_counts() #or

Subject
Math         3
Physics      2
Chemistry    2
Name: count, dtype: int64

In [14]:
df.groupby("Subject").size()

Subject
Chemistry    2
Math         3
Physics      2
dtype: int64

In [15]:
df.sort_values(by="Marks", ascending=False)

       Name   Age  Marks    Subject
3   Shubham  22.0   90.0  Chemistry
2     Karan   NaN   88.0       Math
0      Aman  22.0   85.0       Math
5       NaN  24.0   72.0    Physics
4  Abhishek  25.0   56.0       Math
1    Saurav  23.0    NaN    Physics
6    Sameer  26.0    NaN  Chemistry

In [16]:
df.nlargest(2, "Marks")

      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0       Math

In [19]:
df.nsmallest(1, "Marks") #or

       Name   Age  Marks Subject
4  Abhishek  25.0   56.0    Math

In [22]:
df[df["Marks"] == df["Marks"].min()]

       Name   Age  Marks Subject
4  Abhishek  25.0   56.0    Math

In [24]:
df.isna().sum()

Name       1
Age        1
Marks      2
Subject    0
dtype: int64

In [26]:
df[df["Marks"].isna()]

     Name   Age  Marks    Subject
1  Saurav  23.0    NaN    Physics
6  Sameer  26.0    NaN  Chemistry

In [28]:
cleaned_df = df.dropna()

In [29]:
df.shape
cleaned_df.shape

(3, 4)